function [c, b] = get_truss_properties(Z, coordinates)
    c = zeros(size(Z, 2), 1);
    b = zeros(size(Z, 2), size(Z, 2));
    for truss_index = 1:size(Z, 2)
        connected_nodes = find(Z(:, truss_index));
        c(truss_index, 1) = sqrt( ...
            ( ...
                coordinates(connected_nodes(1), 1) ...
                - coordinates(connected_nodes(2), 1) ...
            )^2 ...
            + ( ...
                coordinates(connected_nodes(1), 2) ...
                - coordinates(connected_nodes(2), 2) ...
            )^2 ...
        );

        degree = atand( ...
            ( ...
                coordinates(connected_nodes(1), 1) ...
                - coordinates(connected_nodes(2), 1) ...
            ) ...
            / ( ...
                coordinates(connected_nodes(1), 2) ...
                - coordinates(connected_nodes(2), 2) ...
            ) ...
        );

        temp_node = [
            2*connected_nodes(1) - 1;
            2*connected_nodes(1);
            2*connected_nodes(2) - 1;
            2*connected_nodes(2)
        ];

        b(temp_node, truss_index) = [
            cosd(degree);
            sind(degree);
            -cosd(degree);
            -sind(degree)
        ];
    end
end