function truss_K = get_K(Z, E)
    truss_K = zeros(2*size(Z, 1), 2*size(Z, 1));

    for truss_index = 1:size(Z, 2)
        connected_nodes = find(Z(:, truss_index));
        truss_lengths(truss_index) = sqrt( ...
            ( ...
                coordinates(connected_nodes(1), 1) ...
                - coordinates(connected_nodes(2), 1) ...
            )^2 ...
            + ( ...
                coordinates(connected_nodes(1), 2) ...
                - coordinates(connected_nodes(2), 2) ...
            )^2 ...
        );
    end
end